export const CHECK_NODE_STATUS_START = 'CHECK_NODE_STATUS_START';
export const CHECK_NODE_STATUS_SUCCESS = 'CHECK_NODE_STATUS_SUCCESS';
export const CHECK_NODE_STATUS_FAILURE = 'CHECK_NODE_STATUS_FAILURE';
export const GET_BLOCK_CONTENT_START = 'GET_BLOCK_CONTENT_START';
export const GET_BLOCK_CONTENT_SUCCESS = 'GET_BLOCK_CONTENT_SUCCESS';
export const GET_BLOCK_CONTENT_FAILURE = 'GET_BLOCK_CONTENT_FAILURE';
